# Generated by ariadne-codegen on 2023-11-11 01:03
# Source: ./schema/query

from typing import Dict

from .async_base_client import AsyncBaseClient
from .get_q1 import GetQ1


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_q1(self) -> GetQ1:
        query = gql(
            """
            query GetQ1 {
              q1 {
                aob
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GetQ1.model_validate(data)
