# Generated by ariadne-codegen on 2023-11-11 01:03
# Source: ./schema/query

from typing import Optional

from scalars import AorB

from .base_model import BaseModel


class GetQ1(BaseModel):
    q1: "GetQ1Q1"


class GetQ1Q1(BaseModel):
    aob: Optional[AorB]


GetQ1.model_rebuild()
GetQ1Q1.model_rebuild()
